# rubyのバージョン
FROM ruby:3.2.2

# コンテナ内の作業ディレクトリ
WORKDIR /app

# 必要なパッケージをインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential nodejs libpq-dev postgresql-client
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

# Gemfile関連のコピー
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# BundlerとGemの依存関係をインストール
RUN gem install bundler
RUN bundle install 

# アプリケーションのソースコード
COPY . /app

# entrypoint.sh スクリプトをコピーして実行可能にする
COPY entrypoint.sh /usr/bin
RUN chmod +x /usr/bin/entrypoint.sh

# コンテナ起動時にentrypoint.sh　スクリプトを実行
ENTRYPOINT ["entrypoint.sh"]

# コンテナの3000番ポートを外部に公開
EXPOSE 3000

# コンテナ起動時のデフォルトコマンド。Railsサーバーを起動
CMD ["rails", "server", "-b", "0.0.0.0"]
