version: "3.9"
services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
    container_name: moviesaga_web
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: